DILCISBoard/E-ARK-CSIP

- implementation/index.md
- removed some unnecessary elements from Ch 5
- updated examples
> EDIT - Remove unnecessary elements

- specification/implementation/metadata/general-requirements/index.md
Added the ` for the dmdSec that were missing
> Added the markings around dmdSec word

- README.md
- specification/implementation/metadata/index.md
- specification/implementation/metadata/mets/index.md
- specification/implementation/structure/index.md
> FIX - Tables of contents

- specification/implementation/structure/folders/index.md
Updated CSIPSTR4 and CSIPSTR12 according to https://github.com/DILCISBoard/E-ARK-CSIP/issues/140
> DNA METS root/representation requirements

- profile/CSIP.xml
Fixed spelling error and empty element
> Fixed spelling error in CSIP16 and removed empty p in CSIP58

- profile/CSIP.xml
XPath text in CSIP111 corrected as well as text error in CSIP112
> Changed  xpath in CSIP111 and corrected spelling in CSIP112

- specification/implementation/structure/folders/index.md
- fixed wording for requirements following A2 group meeting 7/11/28; and
- fixed requirement punctuation.
> REV - Structural requirements wording

- Gemfile
- _config.yml
- archive/index.md
- index.md
- profile/index.md
- schema/index.md
- specification/authors/index.md
- specification/history/index.md
- specification/implementation/considerations/index.md
- specification/implementation/index.md
- specification/implementation/metadata/general-requirements/index.md
- specification/implementation/metadata/index.md
- specification/implementation/metadata/mets/amdsec/index.md
- specification/implementation/metadata/mets/dmdsec/index.md
- specification/implementation/metadata/mets/filesec/index.md
- specification/implementation/metadata/mets/index.md
- specification/implementation/metadata/mets/mets-root/index.md
- specification/implementation/metadata/mets/metsHdr/index.md
- specification/implementation/metadata/mets/structmap/index.md
- specification/implementation/metadata/premis/index.md
- specification/implementation/structure/folders/index.md
- specification/implementation/structure/implementation/index.md
- specification/implementation/structure/index.md
- specification/index.md
- specification/introduction/index.md
- specification/specification/common-ground/index.md
- specification/specification/index.md
- specification/specification/requirements/index.md
- added `Gemfile` for local [Jekyll](https://jekyllrb.com/) serving via [Ruby](https://www.ruby-lang.org/);
- added `_config.yml` for [Jekyll configuration](https://jekyllrb.com/docs/configuration/);
- added [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/) to each Markdown page;
- 'title:' front matter field for all Markdown pages;
- added blank line before lists; and
- fixed bad links in `README.md`.
> FEAT - Jekyll site generation

- specification/implementation/metadata/mets/amdsec/examples.md
- specification/implementation/metadata/mets/dmdsec/examples.md
- specification/implementation/metadata/mets/filesec/examples.md
- specification/implementation/metadata/mets/metshdr/examples.md
- specification/implementation/metadata/mets/structmap/examples.md
- reflects changes made to example id and lablels.
> DOC - Regenerated specification from profile

- schema/DILCISVocabulariesIP.xml
Renamed SMURF to EMS
Removed SMURFSB
Transfered GeoVector and GeoRaster to Geodata
Removal of empty entry
> Updates of EARK terms and delition of an empty entry

- profile/CSIP.xml
- fixed link error in `E-ARK CS IP METS Extension`; and
- removed trailing spaces.
> FIX - link in profile external schema.

- utils/mets-profile-processor/src/main/java/eu/dilcis/csip/MetsProfileProcessor.java
- utils/mets-profile-processor/src/main/java/eu/dilcis/csip/out/MarkdownFormatter.java
- utils/mets-profile-processor/src/main/java/eu/dilcis/csip/out/RequirementTableGenerator.java
- utils/mets-profile-processor/src/main/java/eu/dilcis/csip/out/SchemaAppendixGenerator.java
- utils/mets-profile-processor/src/main/java/eu/dilcis/csip/profile/ControlledVocabulary.java
- utils/mets-profile-processor/src/main/java/eu/dilcis/csip/profile/ExternalSchema.java
- utils/mets-profile-processor/src/main/java/eu/dilcis/csip/profile/MetsProfileXmlHandler.java
- utils/mets-profile-processor/src/main/java/eu/dilcis/csip/profile/Requirement.java
- added appendix for external schema and vocabularies;
- classes to parse and format schema and vocab elements;
- generator for Markdown formatted entries for schema and vocabs; and
- a little refactoring (and a little new mess :( ).
> FEAT - Appendix for schema and vocabularies

- profile/CSIP.xml
Cleaned up comments in the profile.
> Cleaning up comments in the profile.

- profile/CSIP.xml
Added the word METS
Closes #344
> Added explicity that values comes from the METS standards

- profile/CSIP.xml
Added the missing S.
Closes #335
> Fix of CONTENTID

- profile/CSIP.xml
Fixed to uppercase letters.
Closes #338
> Capitalisation of mimetype fix

- specification/implementation/metadata/mets/index.md
Added the correct name of metsHdr
Closes #295
> Correct name on metsHdr element

- specification/implementation/metadata/premis/index.md
Removed embedding option
Closes #227
> Remived embedding as requriment

- profile/CSIP.xml
Removed the word 'is'
Closes #314
> Removed the word 'is'

- profile/CSIP.xml
Changed text so the meaning is clearer that there should be an empty div present in all transmissions.
Closes #381
> Update of text

- profile/CSIP.xml
Clarification of example.
Closes #302
> Clearifiaction upon where the value in the examples originates

- profile/CSIP.xml
Added text to make explanation more clear
Closes #299
> More specific information regaring the ptype of content

- specification/implementation/metadata/mets/mets-root/index.md
Added text about haivng to take into account shut down servers.
Closes #298
> Updated regarding schmea accessability

- profile/CSIP.xml
Change of description of requirement 32
Closes #380
> removed inconsistensy

- specification/implementation/metadata/premis/index.md
- added reference to LOC vocabulary in 5.3.6; and
- tightened text.
> FIX - Reference to LOC vocabulary

- specification/implementation/index.md
Extra "is" is removed
Closes #283
> REmoved extra is

- specification/implementation/metadata/mets/filesec/index.md
> Removed toc as explanation of fileSec

- specification/implementation/metadata/mets/index.md
Changed second limitation to requirements added that its the MEs documentation that should be followed.
Closes #296
> Changed a word and added som extra

- profile/CSIP.xml
> Fixed xpath spelling error

- profile/CSIP.xml
Added the files to point to.
Closes #446
> Added file to point to for vocabs

- profile/CSIP.xml
change of level
closes #266 
closes #300
> change of requriment level

- profile/CSIP.xml
Change of requrirment level and update of text including clarefiation on how to give the ID's.
Closes #272
> Change of requriment level and clarefication in text

- profile/CSIP.xml
- specification/implementation/metadata/mets/amdsec/index.md
Updates regarding the rights metadata and what can be used.
Closes #304
> Rights metadata textual update

- specification/implementation/metadata/mets/mets-root/index.md
- improved opening sentence, fixes #254
- added better explanation of schema use
> FIX - Section 5.3.1 wording

- profile/CSIP.xml
- specification/appendices/index.md
- specification/appendices/schema/index.md
- specification/implementation/structure/folders/index.md
- typo changed use of "is" to "are" for plural;
- typo fixed used of "containg";
- added references to XML schema for clarity.
> FIX - Clarity changes and typos

- specification/specification/principles/index.md
> FIX - Principle 1.7, confusing description.

- specification/index.md
- specification/introduction/index.md
> FIX - removed refs to E-ARK deliverables.

- profile/CSIP.xml
> Simplified the text in the requriment

- profile/CSIP.xml
update of example id's
Connected with #194
> Updated example ids for metsroot element

- profile/CSIP.xml
> Added a requriemnt

- profile/CSIP.xml
Duplication removed.
Closes #348
> Removal of duplication of requriment

- profile/CSIP.xml
- changed the name of the Content Identification attribute to Package Identifer.
> FIX - Content identification name

- specification/implementation/metadata/mets/filesec/index.md
> Possible missing ending of text fixed

- specification/implementation/metadata/general-requirements/index.md
Added information about our fictive examples.
Closes #256
> Info regarding the examples

- profile/CSIP.xml
Clarification in attribute use.
Closes #436
> Updated so its easier to understand when to use the attribute

- profile/CSIP.xml
- specification/implementation/metadata/mets/structmap/index.md
Added where the value is collectecd from.
Closes #453
> Clarification of where the value in CSIP86 comes from

- profile/CSIP.xml
> Unicication of should and cardinality

- utils/mets-profile-processor/src/main/java/eu/dilcis/csip/out/SchemaAppendixGenerator.java
- placed anchors after `### ` headings.
> FIX - Schema Appendix vocab elements

- profile/CSIP.xml
- specification/index.md
- updated version and date in `profile/CSIP.xml` and `specification/index.md`.
> REL - Bumped version details

- specification/specification/principles/index.md
Jjust using one word through out the principle.
Closes #175
> Changed information to component

- profile/CSIP.xml
- improved XML element typograpghy; and
- tidied stock phrases.
> FIX - Profile vocabulary contexts

- specification/implementation/metadata/mets/index.md
uPDATED MONTH AND ADDED LINK TO THE PAGE WITH mets SCHEMAS
Closes #148
> Updated month and added the page for METs schemaS

- specification/implementation/structure/folders/index.md
To unifie the two requriements.
Closes #180
> Changed so CSIPSTR11 is expressed like CSIPSTR13

- specification/specification/principles/index.md
Changed terms following the recommendation in the issue
Closes #176
> Changed terms following recommendations in the issue

- profile/CSIP.xml
Extended description
Closes #451
> Extended the description of checksumtype

- profile/CSIP.xml
> Updated the tools list

- specification/implementation/metadata/general-requirements/index.md
- specification/implementation/metadata/mets/index.md
- specification/introduction/index.md
Added info regarding METS profile and removed where the word is not needed.
Closes #532
> Added wording about the METS Profile needed

- profile/CSIP.xml
> Added link to the mets documentation

- specification/implementation/structure/folders/index.md
More clear about subfolders in the package
Closes #293
> Clarification about subfolders

- specification/specification/principles/index.md
We want the implementation to be made either physical or psychic.
Closes #176
> Softening the language about implementation

- specification/implementation/structure/folders/index.md
so we can make it more precise in the next version if needed.
Closes #249
> Added that it needs to be stated in submission agreement

- specification/introduction/index.md
added github links
Closes #105
> Added links to the other specis github

- specification/specification/principles/index.md
Rewording and change so its not a principle since it is so ambiguous of the meaning of it. Can be added in next version when better wording has been made.
Concerns #245 and #178
> Principle 3.7

- profile/E-ARK-CSIP.xml
Changed from attribute LABEL to USE
> The attribute is USE not LABEL in CSIP62

- profile/E-ARK-CSIP.xml
MAae sure all href's use lower case folder names.
> All href's use lower case folder names

- .travis.yml
- BASE.md
- SITE.md
- SITE_BASE.md
- create-site.sh
- docs/_config.yml
- specification/implementation/structure/index.md
- specification/introduction/index.md
- restructured markdown document using `BASE`, `SITE`, and `SITE_BASE`;
- using two-stage inclusion process to control TOC generation and scope; and
- added Jekyll information to provide full Jekyll theme on local builds.
> FEAT - New GH pages site generation

- profile/E-ARK-CSIP.xml
Change so its upper case in all the correct palces.
> Made sure @USE and @LABEL start with upper case

- profile/E-ARK-CSIP.xml
- specification/metadata.md
- bumped version number in profile `@ID` attribute;
- bumped date in profile & `specifiction/metadata.md`; and
- removed version number from profile title.
> FEAT - Updated profile for v2.0.1 publication

- profile/E-ARK-CSIP.xml
The attribute had the wrong name in the explanation.
Closes #587
> Fixed wrong name of attribute

- profile/E-ARK-CSIP.xml
- specification/implementation/metadata/general-requirements/index.md
- removed duplicate ids causing validation issues; and
- replaced UUID form of IDs with logical names for readability.
> FIX - Duplicate and obtuse IDs

- create-site.sh
- profile/index.md
- specification/metadata.md
- spec-publisher sub-repo updated;
- updated site publication script;
- added new release metadata; and
- links to archive profile versions.
> FEAT: DILCIS branding

- specification/specification/principles/index.md
A general fix of typos, spelling errors and some grammar, along with some minor re-wording of the text. This is not an exhaustive edit of the text.
> Update of minor text errors (principles)

- specification/introduction/index.md
A general fix of typos, spelling errors and some grammar, along with some minor re-wording of the text. This is not an exhaustive edit of the introduction.
> Update of minor text errors (Introduction)

- specification/implementation/metadata/mets/index.md
A general fix of grammar around line 10. This is not an exhaustive edit of the mets section.
.
> Update of minor text errors (mets)

- specification/implementation/metadata/premis/index.md
A general fix of grammar around line 10. This is not an exhaustive edit of the premis section.
.
> Update of minor text errors (premis)

- specification/implementation/considerations/index.md
A general fix of grammar around line 10. This is not an exhaustive edit of the considerations section.
.
> Update of minor text errors (considerations)

- profile/E-ARK-CSIP.xml
Fixed spelling errors following Jaimes lead.
> Fix of spelling errors following Jaimes lead

- .travis.yml
- Gemfile
- update `spec-publisher` project to include requirement reference fixes;
- run docker site creation with user id not root; and
- remove old GH pages theme references.
> FIX: Requirement references

- RELEASENOTES.md
- create-site.sh
- added `RELEASENOTES.md` for v2.0.4;
- added menu item for release notes; and
- fixed xpath contrast.
> FEAT: Release Notes

- RELEASENOTES.md
- create-site.sh
PR to master will trigger an automatic update of GitHub pages site.
> FIX: Menu font size.

- schema/CSIPVocabularyContentInformationType.xml
- schema/DILCISExtensionMETS.xsd
Updates to the CITS vocabulary folloing publication of new specifications
> Updates in CITS Vocabulay

- profile/E-ARK-CSIP-v2-0-4.xml
Creation of the version 2.1 METS profile.
> Creation of version 2.1 of the METS profile

- profile/E-ARK-CSIP.xml
Spelling error corrected
Closes #655
> Fix of spelling error

- profile/E-ARK-CSIP.xml
Changed a should to a must in wording of CSIP113
Closes #652
> Chnage of wording in CSIP113

- profile/E-ARK-CSIP.xml
Rewording in the textual description of CSIP3 with a removal of the linked vocabulary.
Closes #640
> CSIP3 rewording and delation of vocab

- specification/implementation/metadata/mets/mets-root/index.md
Removal of a not needed heading 5.3.1.1
Closes #635
> Removal of a heading

- profile/E-ARK-CSIP.xml
Changed examples in CSIP2 to follow the used vocabulary
Closes #639
> Change of examples in CSIP2

- specification/implementation/metadata/mets/structmap/index.md
Alignment of the heading to follow how the other METS sections headings are made.
Closes #660
> Alignment of heading to the other METS elements

- profile/E-ARK-CSIP.xml
Adjusting the language.
Closes #653
> Adjusting language to the requriment level in CSIP105

- profile/E-ARK-CSIP-v2-1-0.xml
Creation of updated mets profile and adding the mets profile version 2.1.0 to the repository
> Setting up the METS profile for next version

- profile/E-ARK-CSIP.xml
Requriment level changed to should to follow the cardinality and description of the requriment.
Closes #699
> Unification of obligation and cardinality in CSIP96, 100 and 104

- profile/E-ARK-CSIP.xml
Rewording so that the requirement align with CSIPSTR2 and CSIPSTR10.
Closes #700
> Rewording in CSIP1 to align with CSIIPSTR2 and CSIPSTR10

- schema/CSIPVocabularyContentInformationType.xml
- schema/DILCISExtensionMETS.xsd
Update with the new values for the published specifications in the extending attributes XML-schema and the vocabulary describing them.
> Update of version numbers for the specifications to be referenced

- schema/CSIPVocabularyContentCategory.xml
- schema/DILCISVocabularies.rng
The schema have been updated with the possibility to add revsion information and source of the value. The value list have been updated with new values from the value list from LoC and DC.
> Addition of values to the value list and addition of revsion information to the schema
